# Generated by Django 6.0.3 on 2026-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_fooditem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
