# Generated by Django 6.0.3 on 2026-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="foods/"),
        ),
    ]
