# Generated by Django 4.2.29 on 2026-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditem_image'),
        ('food', '0003_alter_fooditem_id_alter_restaurant_id_and_more'),
    ]

    operations = [
    ]
